### ISSUE TITLE
ai2_negamax.cpp: line 83

### ISSUE THREAD

**Issue by hassy09t** [Nyanyan/OthelloAI_Textbook#1]
オセロを作ってみようと思い、noteの記事、コードを読ませていただいています。

playerを入れ替えて次のnega_max()を呼び出すのはわかりますが、この時も「-」にすべきでしょうか？
同一playerが連続するのにNegativeにすると、評価が逆転してしまう気がしました。
理解が間違っていたらすみません。

**Comment by Nyanyan** [comment]
おそらくパスの処理のところ( https://github.com/Nyanyan/OthelloAI_Textbook/blob/main/ai2_negamax.cpp#L48 )だと思いますが、コードはおそらく合っています。例えば黒の手番で探索しているときに黒の手がなかったら、パスとして白の手を探すためにもう一度nega_maxを呼びます。もしマイナスをつけないと、白目線の評価値をそのまま黒の評価値として処理してしまうことになります。この返答でよろしいでしょうか？引き続き疑問がありましたらご連絡ください。
